run: target/classes/com/pessimistic/Aoc.class
	mvn exec:java -Dexec.mainClass="com.pessimistic.Aoc" -Dexec.args="input.txt"

target/classes/com/pessimistic/Aoc.class: src/main/java/com/pessimistic/Aoc.java
	mvn compile

clean:
	mvn clean
