run: target/classes/com/pessimistic/Aoc.class
	mvn exec:java -Dexec.mainClass="com.pessimistic.Aoc"

target/classes/com/pessimistic/Aoc.class: src/main/java/com/pessimistic/Aoc.java src/main/java/com/pessimistic/Landscape.java
	mvn compile

clean:
	mvn clean